spring:
  web:
    resources:
      static-locations: classpath:/uploads/
  mvc:
    static-path-pattern: "/**"
    problemdetails:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:file:./data/mediahub;AUTO_SERVER=TRUE
    username: mediahub
    password: mediahub
    driver-class-name: org.h2.Driver

logging:
  level:
    org.springframework.security: DEBUG
